import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@styles/Home.module.scss';
import learningUnit from '@utils/images/learningUnit.jpg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CAP - Paraffin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/src/public/vercel.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Paraffin</h1>
        <h3>lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi.</h3>
        <div className={styles.imageLeft}>
          <Image src={learningUnit} alt="Imagen home de Paraffin." />
          <div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi. orem ipsum dolor sit amet, consectetur adipiscing
              elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi.
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi. orem ipsum dolor sit amet, consectetur adipiscing
              elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi.
            </p>
          </div>
        </div>

        <div className={styles.howWorks}>
          <div>
            <h2>Curriculums</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi. orem ipsum dolor sit amet, consectetur adipiscing
              elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi.
            </p>
          </div>
          <div>
            <h2>Learning units</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi. orem ipsum dolor sit amet, consectetur adipiscing
              elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi.
            </p>
          </div>
          <div>
            <h2>Resources</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi. orem ipsum dolor sit amet, consectetur adipiscing
              elit. Donec auctor nisl ut nisl ultricies, et ultricies nisl aliquet. Nulla facilisi.
            </p>
          </div>
        </div>

        <div className={styles.linksFooter}>
          <Link href="#">Fintual</Link>
          <Link href="#">Fintualist</Link>
        </div>
      </main>
    </div>
  );
}
